services:
    barbershop_web:
        container_name: barbershop_web
        image: nginx:alpine
        ports:
            - "8060:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - barbershop_app
        networks:
            - barbershop_network
    barbershop_app:
        container_name: barbershop_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - barbershop_db
        volumes:
            - ./:/var/www
        networks:
            - barbershop_network
        ports:
            - "9080:9000"
    barbershop_db:
        image: mysql
        container_name: barbershop_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - barbershop_database:/var/lib/mysql
        networks:
            - barbershop_network
        ports:
            -   "3207:3206"
    barbershop_redis:
        container_name: barbershop_redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6388:6380"
        networks:
            - barbershop_network
    barbershop_node:
        image: node:22
        container_name: barbershop_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5173:5173"  # For Vite development server
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm run build"
        networks:
            - barbershop_network
networks:
    barbershop_network:
        driver: bridge
volumes:
    barbershop_database:


